export const COUNTRY_SUGGESTIONS = [
  'Alemania',
  'Argentina',
  'Belice',
  'Bolivia',
  'Brasil',
  'Canadá',
  'Chile',
  'China',
  'Colombia',
  'Corea del Sur',
  'Costa Rica',
  'Cuba',
  'Ecuador',
  'El Salvador',
  'España',
  'Estados Unidos',
  'Francia',
  'Guatemala',
  'Haití',
  'Honduras',
  'India',
  'Italia',
  'Jamaica',
  'Japón',
  'México',
  'Nicaragua',
  'Países Bajos',
  'Panamá',
  'Paraguay',
  'Perú',
  'Portugal',
  'Reino Unido',
  'República Dominicana',
  'Suiza',
  'Uruguay',
  'Venezuela',
] as const;
