export const HTTP_ERROR_MESSAGES = {
  NETWORK: 'No se pudo conectar con el servidor. Verifica tu conexion a internet.',
  UNAUTHORIZED: 'Tu sesion ha expirado. Por favor inicia sesion nuevamente.',
  FORBIDDEN: 'No tienes permisos para realizar esta accion.',
  NOT_FOUND: 'El recurso solicitado no fue encontrado.',
  COMPANY_CONTEXT_REQUIRED: 'Debes definir una empresa activa para usar el sistema.',
  COMPANY_CONTEXT_NOT_FOUND: (empresaId: string) =>
    `La empresa activa (${empresaId}) no existe en este backend de inventario. Cambia el contexto de empresa o sincroniza la empresa desde el servicio maestro.`,
  UNPROCESSABLE_ENTITY: 'Los datos enviados no son validos. Revisa el formulario e intenta de nuevo.',
  SERVER_ERROR: 'Ocurrio un error en el servidor. Intenta de nuevo mas tarde.',
  UNEXPECTED: (status: number) => `Error inesperado (${status}). Intenta de nuevo.`,
} as const;

export const UI_MESSAGES = {
  EMPTY_VALUE: '-',
  BODEGA_FORM_SCOPE_NOTE: 'Por ahora la bodega guarda datos generales. Capacidad, geolocalizacion, temperatura y layout interno requieren una siguiente fase de backend.',
  BODEGA_CODE_HELP: 'Usa un codigo corto y unico. Despues de crear la bodega, el codigo queda fijo.',
  BODEGA_COUNTRY_HELP: 'Puedes escribir el pais manualmente o elegir una sugerencia.',
  SELECT_BODEGA: 'Selecciona una bodega para ver sus ubicaciones.',
  LOAD_BODEGAS: 'No se pudieron cargar las bodegas. Intenta de nuevo.',
  CREATE_BODEGA: 'No se pudo crear la bodega. Revisa los datos e intenta de nuevo.',
  CREATE_BODEGA_SUCCESS: 'La bodega fue creada correctamente.',
  LOAD_UBICACIONES: 'No se pudieron cargar las ubicaciones. Intenta de nuevo.',
  LOAD_UNIDADES: 'No se pudieron cargar las unidades. Intenta de nuevo.',
  LOAD_STOCK: 'No se pudo cargar el stock. Intenta de nuevo.',
  LOAD_KARDEX: 'No se pudo cargar el kardex. Intenta de nuevo.',
  LOAD_RECEPCIONES: 'No se pudieron cargar las recepciones. Intenta de nuevo.',
  LOAD_TRANSFERENCIAS: 'No se pudieron cargar las transferencias. Intenta de nuevo.',
  CONFIRM_TRANSFERENCIA_SUCCESS: 'La transferencia fue confirmada correctamente.',
  CONFIRM_TRANSFERENCIA_ERROR: 'No se pudo confirmar la transferencia. Intenta de nuevo.',
  DISPATCH_TRANSFERENCIA_SUCCESS: 'La transferencia fue despachada correctamente.',
  DISPATCH_TRANSFERENCIA_ERROR: 'No se pudo despachar la transferencia. Intenta de nuevo.',
  LOAD_AJUSTES: 'No se pudieron cargar los ajustes. Intenta de nuevo.',
  LOAD_PICKING: 'No se pudieron cargar las ordenes de picking. Intenta de nuevo.',
  EXECUTE_PICKING_SUCCESS: 'La orden de picking fue ejecutada correctamente.',
  EXECUTE_PICKING_ERROR: 'No se pudo ejecutar la orden de picking. Intenta de nuevo.',
  LOAD_CONTEOS: 'No se pudieron cargar los conteos fisicos. Intenta de nuevo.',
  APPLY_CONTEO_SUCCESS: 'El conteo fisico fue aplicado correctamente.',
  APPLY_CONTEO_ERROR: 'No se pudo aplicar el conteo fisico. Intenta de nuevo.',
  UPDATE_BODEGA: 'No se pudo actualizar la bodega. Revisa los datos e intenta de nuevo.',
  UPDATE_BODEGA_SUCCESS: 'La bodega fue actualizada correctamente.',
  DEACTIVATE_BODEGA: 'No se pudo desactivar la bodega. Intenta de nuevo.',
  DEACTIVATE_BODEGA_SUCCESS: 'La bodega fue desactivada correctamente.',
  DEACTIVATE_BODEGA_CONFIRM: '¿Estás seguro de que deseas desactivar esta bodega? Esta acción no se puede deshacer.',
  CREATE_UBICACION: 'No se pudo crear la ubicación. Revisa los datos e intenta de nuevo.',
  CREATE_UBICACION_SUCCESS: 'La ubicación fue creada correctamente.',
  UPDATE_UBICACION: 'No se pudo actualizar la ubicación. Revisa los datos e intenta de nuevo.',
  UPDATE_UBICACION_SUCCESS: 'La ubicación fue actualizada correctamente.',
  CREATE_UNIDAD: 'No se pudo crear la unidad. Revisa los datos e intenta de nuevo.',
  CREATE_UNIDAD_SUCCESS: 'La unidad fue creada correctamente.',
  UPDATE_UNIDAD: 'No se pudo actualizar la unidad. Revisa los datos e intenta de nuevo.',
  UPDATE_UNIDAD_SUCCESS: 'La unidad fue actualizada correctamente.',
  LOAD_LOTES: 'No se pudieron cargar los lotes. Intenta de nuevo.',
  UPDATE_LOTE_SUCCESS: 'El lote fue actualizado correctamente.',
  UPDATE_LOTE: 'No se pudo actualizar el lote. Intenta de nuevo.',
  DEV_COMPANY_CONTEXT_HELP: 'Mientras se integra el servicio maestro, puedes cambiar aqui el empresaId que el frontend envia al backend.',
  DEV_COMPANY_CONTEXT_SAVED: (empresaId: number) => `Usando empresa ${empresaId} para las peticiones del frontend.`,
  DEV_COMPANY_CONTEXT_RESET: 'Se restauro el empresaId por defecto del ambiente actual.',
  DEV_COMPANY_CONTEXT_INVALID: 'Ingresa un ID de empresa valido mayor que cero.',
  REQUIRED_FIELD: 'Este campo es obligatorio.',
} as const;
